export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST"
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS"
export const GET_CARDS_FAIL = "GET_CARDS_FAIL"

export const CREATE_CARDS_REQUEST = "CREATE_CARDS_REQUEST"
export const CREATE_CARDS_SUCCESS = "CREATE_CARDS_SUCCESS"
export const CREATE_CARDS_FAIL = "CREATE_CARDS_FAIL"

export const PUT_CARDS_REQUEST = "PUT_CARDS_REQUEST"
export const PUT_CARDS_SUCCESS = "PUT_CARDS_SUCCESS"
export const PUT_CARDS_FAIL = "PUT_CARDS_FAIL"

export const DELETE_CARDS_REQUEST = "DELETE_CARDS_REQUEST"
export const DELETE_CARDS_SUCCESS = "DELETE_CARDS_SUCCESS"
export const DELETE_CARDS_FAIL = "DELETE_CARDS_FAIL"