export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST"
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL"

export const CREATE_COMMENTS_REQUEST = "CREATE_COMMENTS_REQUEST"
export const CREATE_COMMENTS_SUCCESS = "CREATE_COMMENTS_SUCCESS"
export const CREATE_COMMENTS_FAIL = "CREATE_COMMENTS_FAIL"

export const PUT_COMMENTS_REQUEST = "PUT_COMMENTS_REQUEST"
export const PUT_COMMENTS_SUCCESS = "PUT_COMMENTS_SUCCESS"
export const PUT_COMMENTS_FAIL = "PUT_COMMENTS_FAIL"

export const DELETE_COMMENTS_REQUEST = "DELETE_COMMENTS_REQUEST"
export const DELETE_COMMENTS_SUCCESS = "DELETE_COMMENTS_SUCCESS"
export const DELETE_COMMENTS_FAIL = "DELETE_COMMENTS_FAIL"
