export const GET_LIST_INFO_REQUEST = "GET_LIST_INFO_REQUEST";
export const GET_LIST_INFO_SUCCESS = "GET_LIST_INFO_SUCCESS";
export const GET_LIST_INFO_FAIL = "GET_LIST_INFO_FAIL";

export const CREATE_LIST_INFO_REQUEST = "CREATE_LIST_INFO_REQUEST";
export const CREATE_LIST_INFO_SUCCESS = "CREATE_LIST_INFO_SUCCESS";
export const CREATE_LIST_INFO_FAIL = "CREATE_LIST_INFO_FAIL";

export const PUT_LIST_INFO_REQUEST = "PUT_LIST_INFO_REQUEST";
export const PUT_LIST_INFO_SUCCESS = "PUT_LIST_INFO_SUCCESS";
export const PUT_LIST_INFO_FAIL = "PUT_LIST_INFO_FAIL";

export const DELETE_LIST_INFO_REQUEST = "DELETE_LIST_INFO_REQUEST";
export const DELETE_LIST_INFO_SUCCESS = "DELETE_LIST_INFO_SUCCESS";
export const DELETE_LIST_INFO_FAIL = "DELETE_LIST_INFO_FAIL";