export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL";

export const REMOVE_USER_INFO_REQUEST = "REMOVE_USER_INFO_REQUEST";
export const REMOVE_USER_INFO_SUCCESS = "REMOVE_USER_INFO_SUCCESS";
export const REMOVE_USER_INFO_FAIL = "REMOVE_USER_INFO_FAIL";